---
- hosts: juniper
  gather_facts: off
  tasks:
    - junos_command:
        commands: show interfaces terse
      register: interfaces

    - debug:
        msg: "{{ interfaces['stdout_lines'][0][21] }}"

